getHeaderObjectCIT = function () {
	return {
		"PaperCode":"",
		"PaperNo": "",
		"TermsType" : "01",
		"PriceChange" : "Y",
		"Sign": 0,
		"Sector": [],
		"Model": [],
		"Status": "",
		"Createdby": "",
		"Crdate": null,
		"Crtime": null,
		"Cycle":"01",
		"Initiator": "",
		"Action": "",
		"UsrComment": "",
		"UsrLevel": "",
		"Approver1": "",
		"Approver2": "",
		"Approver3": "",
		"Approver4": "",
		"Approver5": "",
		"Approver6": "",
		"Approver7": "",
		"Approver8": "",
		"Nav_Items": [],
		"Nav_DMS": [],
		"Nav_Wf" : []
	}
};
getItemDetailsObjectCIT = function () {
	return {
		"uiFields": {
		    "Error": "Default",
		    "ItemNo": "",
		  },
		"Plant": "",
		"Vendor": "",
		"VName": "",
		"VLocation": "",
		"PartNo": "",
		"PartDesc": "",
		"Currency": "",
		"ExtPrice": "",
		"SettledPrice": "0",
		"ChgPrctng" : "0",
		"ValidFrom":null,
		"CurrentTerm":"",
		"NewPayTerm":"",
		"NewPayTermDesc":"",
		"IncoTerm" : "",
		"NewIncoTerm": "",
		"NewIncoTermDesc": "",
		"PaperCode": "",
		"PaperNo": "",
		"PirNo" : "",
		"Pinforcat": "",
//		"PinfoCatText" : "",
		"DiscountCond":"",
		"Purorg": "",
		"Delete": "",
		"Amndcode": "",
		"AmndcodeDesc": "",
		"Sign": "",
	}
};
getDMSObjectCIT = function () {
	return {
		"Filekey": "",
		"TabId": "",
		"PartNo": "",
		"FrxRmStatus": "",
		"Posnr": "",
		"Doknr": "",
		"Dokar": "",
		"Dokvr": "",
		"Doktl": "",
		"Filename": "",
		"Filedesc": "",
		"Filesize": "",
		"CreatedBy": "",
		"CreatedOn": "",
		"Filecontents": "",
		"FileCatg": "",
		"Delete": ""
	}
};